blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature requests
    url: https://coals.live
    about: Share new feature ideas
  - name: â“ Ask a question
    url: https://coals.live
    about: Ask any question you have
